### PR TITLE
fix: custom fee

### LINKED ISSUE #1792: Using a custom fee is not working
Reported by user and I reproduced the issue. Using the test-app, the custom fee does not change the fee being applied in the app.

Images provided by arkadiko:
image

image

### PR DESCRIPTION
**Pull request by fbwoolf**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/blockstack/ux/actions/runs/1329588579).

This PR fixes using a custom fee not working.

Issue #1792 

cc/ @kyranjamie @beguene

### CODE REVIEW

File: src/pages/transaction-signing/components/actions.tsx [hunk 1]
```diff
@@ -123,12 +124,12 @@ const SubmitAction = (props: ButtonProps) => {
...
   let showWarning = false;
   const defaultFee = useCurrentDefaultFee();
+  const customFee = useTransactionRequestCustomFee();
   const transactionRequest = useTransactionRequest();
   const appName = transactionRequest?.appDetails?.name;
-  const customFee = transactionRequest?.fee;
 
   if (!!customFee && defaultFee) {
-    showWarning = customFee > defaultFee.toNumber() * 4;
+    showWarning = customFee.isGreaterThan(defaultFee.times(4));
```
Comment (kyranjamie) [inline src/pages/transaction-signing/components/actions.tsx]: This is a magic number, see it was there before but a long, descriptive variable makes code much much easier to understand.

```suggestion
    const multipleFromWhichFeeIsConsideredLarge = 4;
    showWarning = customFee.isGreaterThan(defaultFee.times(multipleFromWhichFeeIsConsideredLarge));
```

**Review by kyranjamie — APPROVED** [review]
LGTM @fbwoolf

**Review by beguene — APPROVED** [review]
